routes/web.php
<?php

use UniSharp\LaravelFilemanager\Lfm;

Route::get('/', function () {
    return view('index');
});

Auth::routes(['register' => false]);
// Route::get('/home', 'HomeController@index')->name('home');

////////////
// ADMIN //
///////////
Route::name('admin.')->group(function () {
    // Auth
    Route::namespace('AdminAuth')
        ->group(function () {
            Route::get('/admin/login', 'LoginController@showLoginForm')->name('login');
            Route::post('/admin/login', 'LoginController@login')->name('login.submit');
            Route::post('/admin/logout', 'LoginController@logout')->name('logout');
    });

    // Admin
    Route::namespace('Admin')
        ->group(function () {

            // Dashboard
            Route::get('/admin', 'AdminController@index')
                ->name('home');
            
            // Topik
            Route::get('/admin/topik', 'EventController@topik')
                ->name('topik');
            Route::post('/admin/topik/add', 'EventController@topikAdd')
                ->name('topikAdd');
            Route::get('/admin/topik/edit/{id}', 'EventController@topikEdit')
                ->name('topikEdit');
            Route::post('/admin/topik/update', 'EventController@topikUpdate')
                ->name('topikUpdate');
            Route::post('/admin/topik/delete/{id}', 'EventController@topikDelete')
                ->name('topikDelete');
            Route::post('/admin/topik/aktifkan/{id}', 'EventController@aktifkan')
                ->name('topikAktifkan');
            Route::post('/admin/topik/nonaktifkan/{id}', 'EventController@nonaktifkan')
                ->name('topikNonaktifkan');
        
            // Quiz
            Route::get('/admin/quiz', 'AdminController@quiz')
                ->name('quiz');
            Route::post('/admin/quiz/add', 'AdminController@quizAdd')
                ->name('quizAdd');
            Route::get('/admin/quiz/edit/{id}', 'AdminController@quizEdit')
                ->name('quizEdit');
            Route::post('/admin/quiz/update', 'AdminController@quizUpdate')
                ->name('quizUpdate');
            Route::post('/admin/quiz/delete/{id}', 'AdminController@quizDelete')
                ->name('quizDelete');
        
            // Pertanyaan
            Route::get('/admin/pertanyaan/{id}', 'AdminController@pertanyaan')
                ->name('pertanyaan');
            Route::post('/admin/pertanyaan/image_upload', 'AdminController@pertanyaanImage')
                ->name('upload');
            Route::post('/admin/pertanyaan/add', 'AdminController@pertanyaanAdd')
                ->name('pertanyaanAdd');
            Route::get('/admin/pertanyaan/edit/{id}', 'AdminController@pertanyaanEdit')
                ->name('pertanyaanEdit');
            Route::put('/admin/pertanyaan/update', 'AdminController@pertanyaanUpdate')
                ->name('pertanyaanUpdate');
            Route::delete('/admin/pertanyaan/delete/{id}', 'AdminController@pertanyaanDelete')
                ->name('pertanyaanDelete');
        
            // Jawaban
            Route::get('/admin/jawaban/{id}', 'AdminController@jawaban')
                ->name('jawaban');
            Route::post('/admin/jawaban/add', 'AdminController@jawabanAdd')
                ->name('jawabanAdd');
            Route::get('/admin/jawaban/edit/{id}', 'AdminController@jawabanEdit')
                ->name('jawabanEdit');
            Route::put('/admin/jawaban/update', 'AdminController@jawabanUpdate')
                ->name('jawabanUpdate');
            Route::delete('/admin/jawaban/delete/{id}', 'AdminController@jawabanDelete')
                ->name('jawabanDelete');
        
            // Penilaian
            Route::get('/admin/penilaian', 'AdminController@penilaian')
                ->name('penilaian');
            Route::post('/admin/penilaian/add', 'AdminController@penilaianAdd')
                ->name('penilaianAdd');
            Route::get('/admin/penilaian/edit/{id}', 'AdminController@penilaianEdit')
                ->name('penilaianEdit');
            Route::post('/admin/penilaian/update', 'AdminController@penilaianUpdate')
                ->name('penilaianUpdate');
            Route::post('/admin/penilaian/delete/{id}', 'AdminController@penilaianDelete')
                ->name('penilaianDelete');
        
            // Bank
            Route::get('/admin/bank', 'AdminController@bank')
                ->name('bank');
            Route::post('/admin/bank/add', 'AdminController@bankAdd')
                ->name('bankAdd');
            Route::get('/admin/bank/edit/{id}', 'AdminController@bankEdit')
                ->name('bankEdit');
            Route::post('/admin/bank/update', 'AdminController@bankUpdate')
                ->name('bankUpdate');
            Route::post('/admin/bank/delete/{id}', 'AdminController@bankDelete')
                ->name('bankDelete');
            Route::post('/admin/bank/active/{id}', 'AdminController@bankActive')
                ->name('bankActive');
            Route::post('/admin/bank/inactive/{id}', 'AdminController@bankInActive')
                ->name('bankInActive');
        
            // Export/Import Excel
            Route::get('/admin/user/export/excel', 'AdminController@excel')
                ->name('excel');

            // Tambah Admin
            Route::get('/admin/tambah-admin', 'AdminController@admin')->name('tambahAdmin');
            Route::get('/admin/tambah-admin/edit/{id}', 'AdminController@editAdmin')->name('editAdmin');
            Route::post('/admin/tambah-admin/add', 'AdminController@tambahAdmin')->name('adminAdd');
            Route::post('/admin/tambah-admin/update', 'AdminController@updateAdmin')->name('adminUpdate');
            Route::post('/admin/tambah-admin/delete/{id}', 'AdminController@deleteAdmin')->name('adminDelete');
        
            // User
            Route::get('/admin/user', 'UserController@user')
                ->name('user');
            Route::get('/admin/user/add', 'UserController@userAdd')
                ->name('userAdd');
            Route::post('/admin/user/kota', 'UserController@kota')
                ->name('kota');
            Route::post('/admin/user/insert', 'UserController@userInsert')
                ->name('userInsert');
            Route::post('/admin/user/active/{id}', 'UserController@userActive')
                ->name('userActive');
            Route::post('/admin/user/inactive/{id}', 'UserController@userInactive')
                ->name('userInactive');
            Route::post('/admin/user/delete/{id}', 'UserController@userDelete')
                ->name('userDelete');
            Route::get('/admin/user/detail/{id}', 'UserController@userDetail')
                ->name('userDetail');
        
            // Pembayaran
            Route::get('/admin/pembayaran', 'AdminController@pembayaran')
                ->name('pembayaran');
            Route::get('/admin/pembayaran/bukti/{id}', 'AdminController@pembayaranBukti')
                ->name('pembayaranBukti');
            Route::post('/admin/pembayaran/confirm/{id}', 'AdminController@pembayaranConfirm')
                ->name('pembayaranConfirm');
            Route::post('/admin/pembayaran/batal/{id}', 'AdminController@pembayaranBatal')
                ->name('pembayaranBatal');

            // Sertifikat
            Route::get('/admin/sertifikat', 'AdminController@sertifikat')
            ->name('sertifikat');    
        
            // Leaderboard
            Route::get('/admin/leaderboard', 'LeaderboardController@leaderboard')
                ->name('leaderboard');
            Route::get('/admin/leaderboard/result', 'LeaderboardController@leaderboardResult')
                ->name('leaderboardResult');
        });

    // Import Controller
    Route::get('/admin/user/import/excel', 'ImportController@userImport')
        ->name('import');
    Route::post('/admin/user/import/excel', 'ImportController@importStore')
        ->name('import.submit');
    Route::get('/admin/user/import/panduan', 'ImportController@importGuide')
        ->name('importGuide');
});

Route::group(['prefix' => 'filemanager'], function() {
    Lfm::routes();
});

//////////
// USER //
//////////
Route::name('user.')
    ->group(function () {
        // Auth
        Route::namespace('Auth')
            ->group(function () {
                Route::post('/user/logout', 'LoginController@logoutUser')
                    ->name('logout');
            });
        
        // User
        Route::namespace('User')
            ->group(function () {
                Route::get('/dashboard', 'UserController@index')
                    ->name('dashboard');
                Route::get('/pembayaran', 'UserController@pembayaran')
                    ->name('pembayaran');
                Route::get('/konfirmasi', 'UserController@konfirmasi')
                    ->name('konfirmasi');
                Route::post('/konfirmasi/add', 'UserController@konfirmasiAdd')
                    ->name('konfirmasiAdd');
                Route::get('/status', 'UserController@status')
                    ->name('status');
                Route::get('/exampaper', 'ExampaperController@exampaper')
                    ->name('exampaper');
                Route::get('/exampaper/notfound', 'ExampaperController@notfound')
                    ->name('notfound');
                Route::get('/exampaper/berakhir', 'ExampaperController@berakhir')
                    ->name('berakhir');
                Route::get('/exampaper/kosong', 'ExampaperController@kosong')
                    ->name('kosong');
                Route::get('/lembarsoal/{kode_soal}', 'ExampaperController@lembarsoal')
                    ->name('lembarsoal');
                Route::post('/lembarsoal/submit', 'ExampaperController@storeTest')
                    ->name('storeTest');
            });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-success">User Dashboard</div>

                <div class="card-body">
                    @component('components.who')
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.index')

@section('content')
<header class="uk-cover-container uk-background-cover uk-background-norepeat uk-background-center-center"
style="background-image: url(img/working.jpg);">
    <video src="img/working.mp4" data-uk-cover></video>
    <div class="uk-overlay uk-position-cover uk-overlay-video"></div>
    <div data-uk-sticky="animation: uk-animation-slide-top; sel-target: .uk-navbar-container;
    cls-active: uk-navbar-sticky; cls-inactive: uk-navbar-transparent uk-light; top: 500">
    <br>
        <nav class="uk-navbar-container uk-letter-spacing-small uk-text-bold">
            <div class="uk-container uk-container-large">
                <div class="uk-position-z-index" data-uk-navbar>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-3 col-sm-3">
                                <a class="uk-navbar-item uk-logo" href="/"><img src="{{ asset('img/posi.png') }}" style="max-width: 230px;"></a>
                            </div>
                            <div class="col-lg-5 col-sm-6"></div>
                            <div class="col-lg-4 col-sm-3">
                                <div class="uk-navbar-item">
                                    @if (Route::has('login'))
                                        <div class="top-right links">
                                            @auth
                                                <a href="/dashboard">
                                                    @if(Auth::user()->jenis_kelamin == 'Laki-Laki')
                                                        <img src="{{ asset('img/male.png') }}" alt="User image" width="40">
                                                    @elseif(Auth::user()->jenis_kelamin == 'Perempuan')
                                                        <img src="{{ asset('img/female.png') }}" alt="User image" width="40">
                                                    @endif
                                                    {{ Auth::user()->username }}
                                                </a>
                                                |
                                                <a href="{{ route('user.logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                                </a>

                                                <form id="logout-form" action="{{ route('user.logout') }}" method="POST" style="display: none;">
                                                @csrf
                                                </form>
                                    @else
                                            <div><a class="uk-button uk-button-success-outline" href="/login">Sign In</a></div>
                                            @endauth
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <form action="{{ route('user.exampaper') }}" id="cari" method="get">
    @csrf
        <div class="uk-container uk-container-large uk-light" data-uk-height-viewport="offset-top: true">
            <div data-uk-grid data-uk-height-viewport="offset-top: true">
                <div class="col-lg-2"></div>
                <div class="uk-width-expand@m uk-section uk-flex uk-flex-column" style="margin-top: -100px;">
                    <div class="uk-margin-auto-top uk-margin-auto-bottom" align="left">
                        <div class="uk-grid-collapse uk-width-3-4@m uk-margin-medium-top tes" data-uk-grid
                        data-uk-scrollspy="cls: uk-animation-slide-bottom-medium; delay: 200; repeat: true">

                            <div class="uk-width-expand">
                                <input name="cari" class="uk-input uk-form-large uk-border-remove-right" type="text" placeholder="Temukan Soal">
                            </div>
                            <div class="uk-width-auto">
                                <button type="submit" class="uk-button uk-button-large uk-button-success-outline">Cari</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2"></div>
            </div>

            <div class="row">
                <div class="col-lg-12" style="text-align: center;">
                    <p>Pelatihan Olimpiade Sains Indonesia © 2020 <font color="white">Design by  <a href="https//n56ht.com">Insight MarComm</font></a></p>
                </div>
            </div>
        </div>
    </form>
</header>
@endsection

@section('script')
<script>
    $(document).ready(function () {
        console.log('Halo')
    })
</script>
@endsection