routes/web.php
<?php

use UniSharp\LaravelFilemanager\Lfm;

Route::get('/', function () {
    return view('index');
});

Auth::routes(['register' => false]);
// Route::get('/home', 'HomeController@index')->name('home');

////////////
// ADMIN //
///////////
Route::name('admin.')->group(function () {
    // Auth
    Route::namespace('AdminAuth')
        ->group(function () {
            Route::get('/admin/login', 'LoginController@showLoginForm')->name('login');
            Route::post('/admin/login', 'LoginController@login')->name('login.submit');
            Route::post('/admin/logout', 'LoginController@logout')->name('logout');
    });

    // Admin
    Route::namespace('Admin')
        ->group(function () {

            // Dashboard
            Route::get('/admin', 'AdminController@index')
                ->name('home');
            
            // Topik
            Route::get('/admin/topik', 'EventController@topik')
                ->name('topik');
            Route::post('/admin/topik/add', 'EventController@topikAdd')
                ->name('topikAdd');
            Route::get('/admin/topik/edit/{id}', 'EventController@topikEdit')
                ->name('topikEdit');
            Route::post('/admin/topik/update', 'EventController@topikUpdate')
                ->name('topikUpdate');
            Route::post('/admin/topik/delete/{id}', 'EventController@topikDelete')
                ->name('topikDelete');
            Route::post('/admin/topik/aktifkan/{id}', 'EventController@aktifkan')
                ->name('topikAktifkan');
            Route::post('/admin/topik/nonaktifkan/{id}', 'EventController@nonaktifkan')
                ->name('topikNonaktifkan');
        
            // Quiz
            Route::get('/admin/quiz', 'AdminController@quiz')
                ->name('quiz');
            Route::post('/admin/quiz/add', 'AdminController@quizAdd')
                ->name('quizAdd');
            Route::get('/admin/quiz/edit/{id}', 'AdminController@quizEdit')
                ->name('quizEdit');
            Route::post('/admin/quiz/update', 'AdminController@quizUpdate')
                ->name('quizUpdate');
            Route::post('/admin/quiz/delete/{id}', 'AdminController@quizDelete')
                ->name('quizDelete');
        
            // Pertanyaan
            Route::get('/admin/pertanyaan/{id}', 'AdminController@pertanyaan')
                ->name('pertanyaan');
            Route::post('/admin/pertanyaan/image_upload', 'AdminController@pertanyaanImage')
                ->name('upload');
            Route::post('/admin/pertanyaan/add', 'AdminController@pertanyaanAdd')
                ->name('pertanyaanAdd');
            Route::get('/admin/pertanyaan/edit/{id}', 'AdminController@pertanyaanEdit')
                ->name('pertanyaanEdit');
            Route::put('/admin/pertanyaan/update', 'AdminController@pertanyaanUpdate')
                ->name('pertanyaanUpdate');
            Route::delete('/admin/pertanyaan/delete/{id}', 'AdminController@pertanyaanDelete')
                ->name('pertanyaanDelete');
        
            // Jawaban
            Route::get('/admin/jawaban/{id}', 'AdminController@jawaban')
                ->name('jawaban');
            Route::post('/admin/jawaban/add', 'AdminController@jawabanAdd')
                ->name('jawabanAdd');
            Route::get('/admin/jawaban/edit/{id}', 'AdminController@jawabanEdit')
                ->name('jawabanEdit');
            Route::put('/admin/jawaban/update', 'AdminController@jawabanUpdate')
                ->name('jawabanUpdate');
            Route::delete('/admin/jawaban/delete/{id}', 'AdminController@jawabanDelete')
                ->name('jawabanDelete');
        
            // Penilaian
            Route::get('/admin/penilaian', 'AdminController@penilaian')
                ->name('penilaian');
            Route::post('/admin/penilaian/add', 'AdminController@penilaianAdd')
                ->name('penilaianAdd');
            Route::get('/admin/penilaian/edit/{id}', 'AdminController@penilaianEdit')
                ->name('penilaianEdit');
            Route::post('/admin/penilaian/update', 'AdminController@penilaianUpdate')
                ->name('penilaianUpdate');
            Route::post('/admin/penilaian/delete/{id}', 'AdminController@penilaianDelete')
                ->name('penilaianDelete');
        
            // Bank
            Route::get('/admin/bank', 'AdminController@bank')
                ->name('bank');
            Route::post('/admin/bank/add', 'AdminController@bankAdd')
                ->name('bankAdd');
            Route::get('/admin/bank/edit/{id}', 'AdminController@bankEdit')
                ->name('bankEdit');
            Route::post('/admin/bank/update', 'AdminController@bankUpdate')
                ->name('bankUpdate');
            Route::post('/admin/bank/delete/{id}', 'AdminController@bankDelete')
                ->name('bankDelete');
            Route::post('/admin/bank/active/{id}', 'AdminController@bankActive')
                ->name('bankActive');
            Route::post('/admin/bank/inactive/{id}', 'AdminController@bankInActive')
                ->name('bankInActive');
        
            // Export/Import Excel
            Route::get('/admin/user/export/excel', 'AdminController@excel')
                ->name('excel');

            // Tambah Admin
            Route::get('/admin/tambah-admin', 'AdminController@admin')->name('tambahAdmin');
            Route::get('/admin/tambah-admin/edit/{id}', 'AdminController@editAdmin')->name('editAdmin');
            Route::post('/admin/tambah-admin/add', 'AdminController@tambahAdmin')->name('adminAdd');
            Route::post('/admin/tambah-admin/update', 'AdminController@updateAdmin')->name('adminUpdate');
            Route::post('/admin/tambah-admin/delete/{id}', 'AdminController@deleteAdmin')->name('adminDelete');
        
            // User
            Route::get('/admin/user', 'UserController@user')
                ->name('user');
            Route::get('/admin/user/add', 'UserController@userAdd')
                ->name('userAdd');
            Route::post('/admin/user/kota', 'UserController@kota')
                ->name('kota');
            Route::post('/admin/user/insert', 'UserController@userInsert')
                ->name('userInsert');
            Route::post('/admin/user/active/{id}', 'UserController@userActive')
                ->name('userActive');
            Route::post('/admin/user/inactive/{id}', 'UserController@userInactive')
                ->name('userInactive');
            Route::post('/admin/user/delete/{id}', 'UserController@userDelete')
                ->name('userDelete');
            Route::get('/admin/user/detail/{id}', 'UserController@userDetail')
                ->name('userDetail');
        
            // Pembayaran
            Route::get('/admin/pembayaran', 'AdminController@pembayaran')
                ->name('pembayaran');
            Route::get('/admin/pembayaran/bukti/{id}', 'AdminController@pembayaranBukti')
                ->name('pembayaranBukti');
            Route::post('/admin/pembayaran/confirm/{id}', 'AdminController@pembayaranConfirm')
                ->name('pembayaranConfirm');
            Route::post('/admin/pembayaran/batal/{id}', 'AdminController@pembayaranBatal')
                ->name('pembayaranBatal');

            // Sertifikat
            Route::get('/admin/sertifikat', 'AdminController@sertifikat')
            ->name('sertifikat');    
        
            // Leaderboard
            Route::get('/admin/leaderboard', 'LeaderboardController@leaderboard')
                ->name('leaderboard');
            Route::get('/admin/leaderboard/result', 'LeaderboardController@leaderboardResult')
                ->name('leaderboardResult');
        });

    // Import Controller
    Route::get('/admin/user/import/excel', 'ImportController@userImport')
        ->name('import');
    Route::post('/admin/user/import/excel', 'ImportController@importStore')
        ->name('import.submit');
    Route::get('/admin/user/import/panduan', 'ImportController@importGuide')
        ->name('importGuide');
});

Route::group(['prefix' => 'filemanager'], function() {
    Lfm::routes();
});

//////////
// USER //
//////////
Route::name('user.')
    ->group(function () {
        // Auth
        Route::namespace('Auth')
            ->group(function () {
                Route::post('/user/logout', 'LoginController@logoutUser')
                    ->name('logout');
            });
        
        // User
        Route::namespace('User')
            ->group(function () {
                Route::get('/dashboard', 'UserController@index')
                    ->name('dashboard');
                Route::get('/pembayaran', 'UserController@pembayaran')
                    ->name('pembayaran');
                Route::get('/konfirmasi', 'UserController@konfirmasi')
                    ->name('konfirmasi');
                Route::post('/konfirmasi/add', 'UserController@konfirmasiAdd')
                    ->name('konfirmasiAdd');
                Route::get('/status', 'UserController@status')
                    ->name('status');
                Route::get('/exampaper', 'ExampaperController@exampaper')
                    ->name('exampaper');
                Route::get('/exampaper/notfound', 'ExampaperController@notfound')
                    ->name('notfound');
                Route::get('/exampaper/berakhir', 'ExampaperController@berakhir')
                    ->name('berakhir');
                Route::get('/exampaper/kosong', 'ExampaperController@kosong')
                    ->name('kosong');
                Route::get('/lembarsoal/{kode_soal}', 'ExampaperController@lembarsoal')
                    ->name('lembarsoal');
                Route::post('/lembarsoal/submit', 'ExampaperController@storeTest')
                    ->name('storeTest');
            });
});

resources/views/admin/modals/_admin.blade.php
<div id="modalAdmin" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Admin</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="formAdmin" method="post" data-parsley-validate>
                @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="nama_admin">Nama Admin:</label>
                                <input type="text" name="nama_admin" id="nama_admin" class="form-control" required placeholder="Nama Admin" data-parsley-required-message="Nama tidak boleh kosong.">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="email">E-mail:</label>
                                <input type="text" name="email" id="email" class="form-control" required placeholder="E-Mail" data-parsley-required-message="Email tidak boleh kosong.">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="password">Password:</label>
                                <input type="password" name="password" id="password" class="form-control" required placeholder="Password" data-parsley-required-message="Password tidak boleh kosong.">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="confirm-password">Konfirmasi Password:</label>
                                <input type="password" name="confirm-password" id="confirm-password" onchange="check();" class="form-control" required placeholder="Password" data-parsley-required-message="Konfirmasi password terlebih dahulu.">
                                <span id="tes"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="hidden" name="hidden_id" id="id">
                            <input type="hidden" name="add" id="tambah" value="Tambah">
                            <input class="btn btn-primary btn-block" type="submit" id="action" value="tambah">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/_bank.blade.php
<div id="modalBank" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Rekening</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="formBank" method="post">
                @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="nama_bank">Nama Bank:</label>
                                <input type="text" name="nama_bank" id="nama_bank" class="form-control" required placeholder="Nama bank">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="nama_pemilik">Nama Pemegang Akun:</label>
                                <input type="text" name="nama_pemilik" id="nama_pemilik" class="form-control" required placeholder="Nama pemilik">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="no_rekening">No. Rekening</label>
                                <input type="text" name="no_rekening" id="no_rekening" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" class="form-control" required placeholder="No. Rekening">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="hidden" name="hidden_id" id="id">
                            <input type="hidden" name="add" id="tambah" value="Tambah">
                            <input class="btn btn-primary btn-block" type="submit" id="action" value="tambah">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/_bukti.blade.php
<div id="modalBukti" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Bukti Pembayaran</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <img src="" id="bukti" alt="Bukti Pembayaran">
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/_leaderboard.blade.php
<div class="row">
    <div class="col-xl-12">
        <div class="card-box">
            <div class="row">
                <div class="col-12">
                    <form class="form-inline" action="{{ route('admin.leaderboardResult') }}" method="GET">
                        @csrf
                        <div class="form-group mb-2">
                            <label for="staticEmail2">Sort by:</label>
                        </div>
                        <div class="form-group mx-sm-3 mb-2">
                            <label class="sr-only">Password</label>
                            <select class="form-control" name="event">
                                @forelse ($events as $event)
                                    <option value="{{ $event->id }}">{{ $event->nama_olimpiade }} - {{ $event->tingkat }}</option>
                                @empty
                                    <option selected>Belum ada event.</option>
                                @endforelse
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary mb-2" {{ empty($event) ? 'disabled' : '' }}>Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/_penilaian.blade.php
<div id="modalPenilaian" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Penilaian</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="formPenilaian" method="post" data-parsley-validate>
                @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="nama_penilaian">Nama Penilaian:</label>
                                <input type="text" name="nama_penilaian" id="nama_penilaian" class="form-control" required placeholder="Nama Penilaian" data-parsley-required-message="Nama penilaian tidak boleh kosong.">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="level">Level:</label>
                                <select name="level" id="level" class="form-control" required>
                                    <option value="">Pilih</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <h4>Benar</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="pointA">Point Awal:</label>
                                <input type="text" oninput="pekalian()" name="pointA" id="pointA" class="form-control" required data-parsley-required-message="Point awal harus diisi">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="perkalian">Dikalikan:</label>
                                <input type="text" oninput="pekalian()" name="perkalian" id="perkalian" class="form-control" required data-parsley-required-message="Perkaliann harus diisi.">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="benar">Point Benar</label>
                                <input type="text" name="benar" id="benar" class="form-control" readonly>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col">
                            <h4>Salah</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="pointB">Point Awal:</label>
                                <input type="text" oninput="pekalianB()" name="pointB" id="pointB" class="form-control" required data-parsley-required-message="Point awal tidak boleh kosong.">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="perkalianB">Dikalikan:</label>
                                <input type="text" oninput="pekalianB()" name="perkalianB" id="perkalianB" class="form-control" required data-parsley-required-message="Perkalian tidak boleh kosong.">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="salah">Point Salah</label>
                                <input type="text" name="salah" id="salah" class="form-control" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="hidden" name="hidden_id" id="id">
                            <input type="hidden" name="add" id="tambah" value="Tambah">
                            <input class="btn btn-primary btn-block" type="submit" id="action" value="tambah">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/_quiz.blade.php
<div id="modalQuiz" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Topik</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="formQuiz" method="post" data-parsley-validate>
                @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="olimpiade_id">Pilih Kategori:</label>
                                <select name="olimpiade_id" id="olimpiade_id" class="form-control" required>
                                    <option value="">Pilih</option>
                                    @foreach($olimpiades as $olimpiade)
                                    <option value="{{ $olimpiade->id }}">{{ $olimpiade->nama_olimpiade }} {{ $olimpiade->tingkat }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="waktu">Waktu:</label>
                                <div class="input-group">
                                    <input type="text" name="waktu" id="waktu" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" required placeholder="0" data-parsley-required-message="Waktu tidak boleh kosong.">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">menit</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="kode_soal">Kode soal:</label>
                                <input type="text" id="randomString" class="form-control" name="kode_soal" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="hidden" name="hidden_id" id="id">
                            <input type="hidden" name="add" id="tambah" value="Tambah">
                            <input class="btn btn-primary btn-block" type="submit" id="action" value="tambah">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/_topik.blade.php
<div id="modalTopik" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Topik</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="formTopik" method="post" data-parsley-validate>
                @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="nama_olimpiade">Event-Bidang:</label>
                                <input type="text" name="nama_olimpiade" id="nama_olimpiade" class="form-control" placeholder="Event-Bidang" autocomplete="off" required data-parsley-required-message="Event-Bidang harus di isi!">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="tingkat">Tingkat:</label>
                                <select name="tingkat" id="tingkat" class="form-control" required>
                                    <option value="">Pilih</option>
                                    <option value="siswaSD">SD (Siswa)</option>
                                    <option value="siswaSMP">SMP (Siswa)</option>
                                    <option value="siswaSMA">SMA (Siswa)</option>
                                    <option value="guruSD">SD (Guru)</option>
                                    <option value="guruSMP">SMP (Guru)</option>
                                    <option value="guruSMA">SMA (Guru)</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="start_date">Tanggal Mulai:</label>
                                <input type="text" name="start_date" id="start_date" class="start_date form-control" placeholder="Tanggal Mulai Event">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="end_date">Tanggal Selesai:</label>
                                <input type="text" name="end_date" id="end_date" class="end_date form-control" placeholder="Tanggal Selesai Event">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="deskripsi">Deskripsi:</label>
                                <textarea class="form-control" name="deskripsi" id="deskripsi" cols="10" rows="4" required placeholder="Deskripsi Event" data-parsley-required-message="Deskripsi tidak boleh kosong!"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="hidden" name="hidden_id" id="id">
                            <input type="hidden" name="add" id="tambah" value="Tambah">
                            <input class="btn btn-primary btn-block" type="submit" id="action" value="tambah">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/modals/_user.blade.php
<div id="modalUser" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Topik</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <table class="table table-bordered">
                    <tr>
                        <th>Nama:</th>
                        <td id="nama_lengkap"></td>
                        <th rowspan=6></th>
                        <th>Asal Sekolah:</th>
                        <td id="asal_sekolah"></td>
                    </tr>
                    <tr>
                        <th>Jenis Kelamin:</th>
                        <td id="jenis_kelamin"></td>
                        <th>Provinsi:</th>
                        <td id="provinsi_id"></td>
                    </tr>
                    <tr>
                        <th>Tanggal Lahir:</th>
                        <td id="tanggal_lahir"></td>
                        <th>Kecamatan/Kota:</th>
                        <td id="kabupaten_kota_id"></td>
                    </tr>
                    <tr>
                        <th>Tempat Lahir:</th>
                        <td id="tempat_lahir"></td>
                        <th>Kelas:</th>
                        <td id="kelas"></td>
                    </tr>
                    <tr>
                        <th>Alamat:</th>
                        <td id="alamat"></td>
                        <th>E-mail:</th>
                        <td id="email"></td>
                    </tr>
                    <tr>
                        <th>No. Telp/Whatsapp:</th>
                        <td id="no_telepon_whatsapp"></td>
                        <th>Status:</th>
                        <td id="is_active"></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>