routes/web.php
<?php

use UniSharp\LaravelFilemanager\Lfm;

Route::get('/', function () {
    return view('index');
});

Auth::routes(['register' => false]);
// Route::get('/home', 'HomeController@index')->name('home');

////////////
// ADMIN //
///////////
Route::name('admin.')->group(function () {
    // Auth
    Route::namespace('AdminAuth')
        ->group(function () {
            Route::get('/admin/login', 'LoginController@showLoginForm')->name('login');
            Route::post('/admin/login', 'LoginController@login')->name('login.submit');
            Route::post('/admin/logout', 'LoginController@logout')->name('logout');
    });

    // Admin
    Route::namespace('Admin')
        ->group(function () {

            // Dashboard
            Route::get('/admin', 'AdminController@index')
                ->name('home');
            
            // Topik
            Route::get('/admin/topik', 'EventController@topik')
                ->name('topik');
            Route::post('/admin/topik/add', 'EventController@topikAdd')
                ->name('topikAdd');
            Route::get('/admin/topik/edit/{id}', 'EventController@topikEdit')
                ->name('topikEdit');
            Route::post('/admin/topik/update', 'EventController@topikUpdate')
                ->name('topikUpdate');
            Route::post('/admin/topik/delete/{id}', 'EventController@topikDelete')
                ->name('topikDelete');
            Route::post('/admin/topik/aktifkan/{id}', 'EventController@aktifkan')
                ->name('topikAktifkan');
            Route::post('/admin/topik/nonaktifkan/{id}', 'EventController@nonaktifkan')
                ->name('topikNonaktifkan');
        
            // Quiz
            Route::get('/admin/quiz', 'AdminController@quiz')
                ->name('quiz');
            Route::post('/admin/quiz/add', 'AdminController@quizAdd')
                ->name('quizAdd');
            Route::get('/admin/quiz/edit/{id}', 'AdminController@quizEdit')
                ->name('quizEdit');
            Route::post('/admin/quiz/update', 'AdminController@quizUpdate')
                ->name('quizUpdate');
            Route::post('/admin/quiz/delete/{id}', 'AdminController@quizDelete')
                ->name('quizDelete');
        
            // Pertanyaan
            Route::get('/admin/pertanyaan/{id}', 'AdminController@pertanyaan')
                ->name('pertanyaan');
            Route::post('/admin/pertanyaan/image_upload', 'AdminController@pertanyaanImage')
                ->name('upload');
            Route::post('/admin/pertanyaan/add', 'AdminController@pertanyaanAdd')
                ->name('pertanyaanAdd');
            Route::get('/admin/pertanyaan/edit/{id}', 'AdminController@pertanyaanEdit')
                ->name('pertanyaanEdit');
            Route::put('/admin/pertanyaan/update', 'AdminController@pertanyaanUpdate')
                ->name('pertanyaanUpdate');
            Route::delete('/admin/pertanyaan/delete/{id}', 'AdminController@pertanyaanDelete')
                ->name('pertanyaanDelete');
        
            // Jawaban
            Route::get('/admin/jawaban/{id}', 'AdminController@jawaban')
                ->name('jawaban');
            Route::post('/admin/jawaban/add', 'AdminController@jawabanAdd')
                ->name('jawabanAdd');
            Route::get('/admin/jawaban/edit/{id}', 'AdminController@jawabanEdit')
                ->name('jawabanEdit');
            Route::put('/admin/jawaban/update', 'AdminController@jawabanUpdate')
                ->name('jawabanUpdate');
            Route::delete('/admin/jawaban/delete/{id}', 'AdminController@jawabanDelete')
                ->name('jawabanDelete');
        
            // Penilaian
            Route::get('/admin/penilaian', 'AdminController@penilaian')
                ->name('penilaian');
            Route::post('/admin/penilaian/add', 'AdminController@penilaianAdd')
                ->name('penilaianAdd');
            Route::get('/admin/penilaian/edit/{id}', 'AdminController@penilaianEdit')
                ->name('penilaianEdit');
            Route::post('/admin/penilaian/update', 'AdminController@penilaianUpdate')
                ->name('penilaianUpdate');
            Route::post('/admin/penilaian/delete/{id}', 'AdminController@penilaianDelete')
                ->name('penilaianDelete');
        
            // Bank
            Route::get('/admin/bank', 'AdminController@bank')
                ->name('bank');
            Route::post('/admin/bank/add', 'AdminController@bankAdd')
                ->name('bankAdd');
            Route::get('/admin/bank/edit/{id}', 'AdminController@bankEdit')
                ->name('bankEdit');
            Route::post('/admin/bank/update', 'AdminController@bankUpdate')
                ->name('bankUpdate');
            Route::post('/admin/bank/delete/{id}', 'AdminController@bankDelete')
                ->name('bankDelete');
            Route::post('/admin/bank/active/{id}', 'AdminController@bankActive')
                ->name('bankActive');
            Route::post('/admin/bank/inactive/{id}', 'AdminController@bankInActive')
                ->name('bankInActive');
        
            // Export/Import Excel
            Route::get('/admin/user/export/excel', 'AdminController@excel')
                ->name('excel');

            // Tambah Admin
            Route::get('/admin/tambah-admin', 'AdminController@admin')->name('tambahAdmin');
            Route::get('/admin/tambah-admin/edit/{id}', 'AdminController@editAdmin')->name('editAdmin');
            Route::post('/admin/tambah-admin/add', 'AdminController@tambahAdmin')->name('adminAdd');
            Route::post('/admin/tambah-admin/update', 'AdminController@updateAdmin')->name('adminUpdate');
            Route::post('/admin/tambah-admin/delete/{id}', 'AdminController@deleteAdmin')->name('adminDelete');
        
            // User
            Route::get('/admin/user', 'UserController@user')
                ->name('user');
            Route::get('/admin/user/add', 'UserController@userAdd')
                ->name('userAdd');
            Route::post('/admin/user/kota', 'UserController@kota')
                ->name('kota');
            Route::post('/admin/user/insert', 'UserController@userInsert')
                ->name('userInsert');
            Route::post('/admin/user/active/{id}', 'UserController@userActive')
                ->name('userActive');
            Route::post('/admin/user/inactive/{id}', 'UserController@userInactive')
                ->name('userInactive');
            Route::post('/admin/user/delete/{id}', 'UserController@userDelete')
                ->name('userDelete');
            Route::get('/admin/user/detail/{id}', 'UserController@userDetail')
                ->name('userDetail');
        
            // Pembayaran
            Route::get('/admin/pembayaran', 'AdminController@pembayaran')
                ->name('pembayaran');
            Route::get('/admin/pembayaran/bukti/{id}', 'AdminController@pembayaranBukti')
                ->name('pembayaranBukti');
            Route::post('/admin/pembayaran/confirm/{id}', 'AdminController@pembayaranConfirm')
                ->name('pembayaranConfirm');
            Route::post('/admin/pembayaran/batal/{id}', 'AdminController@pembayaranBatal')
                ->name('pembayaranBatal');

            // Sertifikat
            Route::get('/admin/sertifikat', 'AdminController@sertifikat')
            ->name('sertifikat');    
        
            // Leaderboard
            Route::get('/admin/leaderboard', 'LeaderboardController@leaderboard')
                ->name('leaderboard');
            Route::get('/admin/leaderboard/result', 'LeaderboardController@leaderboardResult')
                ->name('leaderboardResult');
        });

    // Import Controller
    Route::get('/admin/user/import/excel', 'ImportController@userImport')
        ->name('import');
    Route::post('/admin/user/import/excel', 'ImportController@importStore')
        ->name('import.submit');
    Route::get('/admin/user/import/panduan', 'ImportController@importGuide')
        ->name('importGuide');
});

Route::group(['prefix' => 'filemanager'], function() {
    Lfm::routes();
});

//////////
// USER //
//////////
Route::name('user.')
    ->group(function () {
        // Auth
        Route::namespace('Auth')
            ->group(function () {
                Route::post('/user/logout', 'LoginController@logoutUser')
                    ->name('logout');
            });
        
        // User
        Route::namespace('User')
            ->group(function () {
                Route::get('/dashboard', 'UserController@index')
                    ->name('dashboard');
                Route::get('/pembayaran', 'UserController@pembayaran')
                    ->name('pembayaran');
                Route::get('/konfirmasi', 'UserController@konfirmasi')
                    ->name('konfirmasi');
                Route::post('/konfirmasi/add', 'UserController@konfirmasiAdd')
                    ->name('konfirmasiAdd');
                Route::get('/status', 'UserController@status')
                    ->name('status');
                Route::get('/exampaper', 'ExampaperController@exampaper')
                    ->name('exampaper');
                Route::get('/exampaper/notfound', 'ExampaperController@notfound')
                    ->name('notfound');
                Route::get('/exampaper/berakhir', 'ExampaperController@berakhir')
                    ->name('berakhir');
                Route::get('/exampaper/kosong', 'ExampaperController@kosong')
                    ->name('kosong');
                Route::get('/lembarsoal/{kode_soal}', 'ExampaperController@lembarsoal')
                    ->name('lembarsoal');
                Route::post('/lembarsoal/submit', 'ExampaperController@storeTest')
                    ->name('storeTest');
            });
});

resources/views/admin/pages/jawaban.blade.php
@extends('admin.layouts.master')

@section('title', 'Jawaban')

@section('page-title', 'Buat Jawaban')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box">
                @if(session()->has('message'))
                    <div class="alert alert-success text-success alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Sukses! </strong>{{ session()->get('message') }}
                    </div>
                @elseif(session()->has('hapus'))
                    <div class="alert alert-danger text-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Sukses! </strong>{{ session()->get('hapus') }}
                    </div>
                @endif
                <h4 class="header-title mb-2">Pertanyaan:</h4>
                <p class="sub-header">
                    {!! $pertanyaans->pertanyaan !!}
                </p>
                <hr>
                <h4 class="header-title mt-2">Tulis Jawaban:</h4>
                <form action="{{ route('admin.jawabanAdd') }}" method="post">
                    @csrf
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <textarea name="jawaban" id="summernote" required></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="correct">Benar/Salah:</label>
                                <select name="correct" id="correct" class="form-control" required>
                                    <option value="">Pilih</option>
                                    <option value="Y">Benar</option>
                                    <option value="N">Salah</option>
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="penilaian_id">Jenis Penilaian:</label>
                                <select name="penilaian_id" id="penilaian_id" class="form-control" required>
                                    <option value="">Pilih</option>
                                    @foreach($penilaians as $penilaian)
                                    <option value="{{ $penilaian->id }}">{{ $penilaian->nama_penilaian }} - Level {{ $penilaian->level }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="pertanyaan_id" value="{{ $pertanyaans->id }}">
                    <input type="submit" value="Submit" class="btn btn-rounded btn-primary">
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box table-responsive">
                <h4 class="header-title">Daftar Jawaban</h4>
                <table id="datatable" class="table table-bordered  dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Jawaban</th>
                            <th>Correct</th>
                            <th>Jenis Penilaian</th>
                            <th class="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pertanyaans->jawabans as $key => $j)
                        <tr>
                            <td>{{ ++$key }}</td>
                            <td>{!! $j->jawaban !!}</td>
                            @if($j->correct == 'Y')
                            <td>Benar</td>
                            @else
                            <td>Salah</td>
                            @endif
                            <td>{{ $j->penilaian->nama_penilaian }}/Level: {{ $j->penilaian->level }}</td>
                            <td class="text-center">
                                <form action="{{ route('admin.jawabanDelete', $j->id) }}" method="POST">
                                    <a href="{{ route('admin.jawabanEdit', $j->id) }}" class="btn btn-rounded btn-info" title="Edit"><i class="mdi mdi-pencil"></i></a>
                                    &nbsp;
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-rounded btn-danger" title="Hapus"><i class="mdi mdi-trash-can"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script src="{{ asset('assets/admin/js/jawaban.js') }}"></script>
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script>
    CKEDITOR.replace('summernote', {
        filebrowserImageBrowseUrl: '/filemanager?type=Images',
        filebrowserImageUploadUrl: '/filemanager/upload?type=Images&_token=',
        filebrowserBrowseUrl: '/filemanager?type=Files',
        filebrowserUploadUrl: '/filemanager/upload?type=Files&_token='
    });
</script>
@endsection

resources/views/admin/pages/jawabanEdit.blade.php
@extends('admin.layouts.master')

@section('title', 'Edit Jawaban')

@section('page-title', 'Edit Jawaban')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box">
                <h4 class="header-title mb-2">Pertanyaan:</h4>
                <p class="sub-header">
                    {!! $jawabans->pertanyaan->pertanyaan !!}
                </p>
                <hr>
                <h4 class="header-title mt-2">Ubah Jawaban:</h4>
                <form action="{{ route('admin.jawabanUpdate') }}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <textarea name="jawaban" id="summernote" required>{{ $jawabans->jawaban }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="correct">Benar/Salah:</label>
                                <select name="correct" id="correct" class="form-control" required>
                                    <option value="Y" {{ $jawabans->correct == 'Y' ? 'selected' : '' }}>Benar</option>
                                    <option value="N" {{ $jawabans->correct == 'N' ? 'selected' : '' }}>Salah</option>
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="penilaian_id">Jenis Penilaian:</label>
                                <select name="penilaian_id" id="penilaian_id" class="form-control">
                                    @foreach($penilaians as $p)
                                        <option value="{{ $p->id }}" {{ $jawabans->penilaian->id == $p->id ? 'selected' : '' }}>{{ $p->nama_penilaian }} - Level {{ $p->level }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="hidden_id" value="{{ $jawabans->id }}">
                    <input type="hidden" name="pertanyaan_id" value="{{ $jawabans->pertanyaan_id }}">
                    <input type="submit" value="Update" class="btn btn-rounded btn-primary">
                    <a href="{{ route('admin.jawaban', $jawabans->pertanyaan_id) }}" class="btn btn-rounded btn-warning">Batal</a>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script>
    CKEDITOR.replace('summernote', {
        filebrowserImageBrowseUrl: '/filemanager?type=Images',
        filebrowserImageUploadUrl: '/filemanager/upload?type=Images&_token=',
        filebrowserBrowseUrl: '/filemanager?type=Files',
        filebrowserUploadUrl: '/filemanager/upload?type=Files&_token='
    });
</script>
@endsection

resources/views/admin/pages/pertanyaanEdit.blade.php
@extends('admin.layouts.master')

@section('title', 'Edit Pertanyaan')

@section('page-title', 'Edit Pertanyaan')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box">
                <h4 class="header-title mb-2">Kategori: <strong>{{ $pertanyaans->quiz->olimpiade->nama_olimpiade }} {{ $pertanyaans->quiz->olimpiade->tingkat }} ({{ $pertanyaans->quiz->kode_soal }})</strong></h4>
                <hr>
                <h4 class="header-title mt-2">Ubah Pertanyaan:</h4>
                <form action="{{ route('admin.pertanyaanUpdate') }}" method="post">
                @csrf
                @method('PUT')
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <textarea name="pertanyaan" id="summernote" class="form-control">{{ $pertanyaans->pertanyaan }}</textarea>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="id" value="{{ $pertanyaans->id }}">
                    <input type="hidden" name="quiz_id" value="{{ $pertanyaans->quiz->id }}">
                    <input type="submit" value="Update" class="btn btn-rounded btn-primary">
                    <a href="{{ route('admin.pertanyaan', $pertanyaans->quiz->id) }}" class="btn btn-rounded btn-warning">Batal</a>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script>
    CKEDITOR.replace('summernote', {
        filebrowserImageBrowseUrl: '/filemanager?type=Images',
        filebrowserImageUploadUrl: '/filemanager/upload?type=Images&_token=',
        filebrowserBrowseUrl: '/filemanager?type=Files',
        filebrowserUploadUrl: '/filemanager/upload?type=Files&_token='
    });
</script>
@endsection

resources/views/admin/pages/quiz.blade.php
@extends('admin.layouts.master')

@section('title', 'Quiz')

@section('page-title', 'Quiz')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box table-responsive">
                <h4 class="header-title mb-2">Quiz</h4>
                <button type="button" class="sub-header btn btn-rounded btn-sm btn-primary text-white" id="tambah"><i class="fa fa-plus"></i></button>
                <table id="datatable" class="table table-bordered  dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead class="text-center">
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>Kategori</th>
                            <th>Kode Soal</th>
                            <th>Waktu</th>
                            <th>Jumlah Pertanyaan</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        @php
                            $no = 0;
                        @endphp
                        @foreach($quizzes as $q)
                        @php
                            $no++;
                        @endphp
                        @if($q->olimpiade)
                        <tr>
                            <td>{{ $no }}</td>
                            <td>{{ $q->id }}</td>
                            <td>
                                {{ $q->olimpiade->nama_olimpiade }} {{ $q->olimpiade->tingkat }}
                            </td>
                            <td>{{ $q->kode_soal }}</td>
                            <td>{{ $q->waktu }} menit</td>
                            <td>{{ $q->pertanyaans->count() }}</td>
                            <td>
                                <a href="{{ route('admin.pertanyaan', $q->id) }}" class="btn btn-warning btn-rounded" title="Buat Pertanyaan"><i class="mdi mdi-pencil-plus"></i></a>
                                &nbsp;
                                <a href="#" class="edit btn btn-rounded btn-info" id="{{ $q->id }}" title="Edit"><i class="mdi mdi-pencil"></i></a>
                                &nbsp;
                                <a href="#" class="hapus btn btn-rounded btn-danger" onclick="deleteConfirmation({{ $q->id }})" title="Hapus"><i class="mdi mdi-trash-can"></i></a>
                            </td>
                            @else
                            <td>{{ $no }}</td>
                            <td>
                                <span class="text-danger">Kategori telah dihapus</span>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@include('admin.modals._quiz')
@endsection

@section('script')
<script src="{{ asset('assets/admin/js/quiz.js') }}"></script>
@endsection

resources/views/admin/pages/sertifikat.blade.php
@extends('admin.layouts.master')

@section('title', 'Sertifikat')

@section('page-title', 'Sertifikat')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box table-responsive">
                <h4 class="header-title mb-2">Sertifikat</h4>

            </div>
        </div>
    </div>           
@endsection

resources/views/admin/pages/user.blade.php
@extends('admin.layouts.master')

@section('title', 'User')

@section('page-title', 'Semua User')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box table-responsive">
                @if (session()->has('success'))
                <div class="alert alert-success">
                    <strong>Sukses!</strong> {{ session('success') }}
                </div>
                @elseif (session()->has('imported'))
                <div class="alert alert-success">
                    <strong>Sukses!</strong> {{ session('imported') }}
                </div>
                @endif
                <h4 class="header-title mb-2">User</h4>
                <a href="{{ route('admin.userAdd') }}" class="sub-header btn btn-rounded btn-sm btn-primary text-white"><i class="fa fa-plus"></i></a>
                <a href="{{ route('admin.excel') }}" class="btn text-white btn-sm btn-rounded btn-success sub-header" target="_blank"><i class="mdi mdi-file-excel"></i></a>
<a class="btn btn-sm sub-header text-white btn-rounded btn-info" href="{{ route('admin.import') }}"><i class="mdi mdi-upload"></i></a>
                <table id="datatable" class="table table-bordered  dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead class="text-center">
                        <tr>
                            <th>#</th>
                            <th>Nama Lengkap</th>
                            <th>L/P</th>
                            <th>Tgl. Lahir</th>
                            <th>No. Telp</th>
                            <th>Olimpiade</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        @forelse($users as $key => $user)
                        <tr>
                            <td>{{ ++$key }}</td>
                            <td>{{ $user->nama_lengkap }}</td>
                            @if($user->jenis_kelamin == 'Laki-Laki' || $user->jenis_kelamin == 'laki-laki' || $user->jenis_kelamin == 'Laki-laki')
                            <td>L</td>
                            @elseif($user->jenis_kelamin == 'Perempuan' || $user->jenis_kelamin == 'perempuan')
                            <td>P</td>
                            @endif
                            <td>{{ date('d M Y', strtotime($user->tanggal_lahir)) }}</td>
                            <td>{{ $user->no_telepon_whatsapp }}</td>
                            <td>{{ implode(', ', $user->olimpiades()->get()->pluck('nama_olimpiade')->toArray()) }}</td>
                            @if($user->is_active == 0)
                            <td><span class="badge badge-pill badge-danger">Inactive</span></td>
                            @else
                            <td><span class="badge badge-pill badge-success">Active</span></td>
                            @endif
                            <td>
                                @if($user->is_active == 0)
                                <a href="#" class="btn btn-rounded btn-success" title="Aktifkan User" onclick="active({{ $user->id }})"><i class="mdi mdi-power"></i></a>
                                @else
                                <a href="#" class="btn btn-rounded btn-warning" title="Suspend User" onclick="inactive({{ $user->id }})"><i class="mdi mdi-power"></i></a>
                                @endif
                                &nbsp;
                                <a href="#" class="detail btn btn-rounded btn-info" title="Detail User" id="{{ $user->id }}"><i class="mdi mdi-eye"></i></a>
                                &nbsp;
                                <a href="#" class="btn btn-rounded btn-danger" onclick="deleteConfirmation({{ $user->id }})" title="Hapus User"><i class="mdi mdi-trash-can"></i></a>
                            </td>
                        </tr>
                        @empty
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@include('admin.modals._user')
@endsection

@section('script')
<script src="{{ asset('assets/admin/js/user.js') }}"></script>
@endsection

resources/views/admin/pages/userGuide.blade.php
@extends('admin.layouts.master')

@section('title', 'Petunjuk')

@section('page-title', 'Petunjuk Pengisian')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box">
				<h4 class="header-title mb-2">Silahkan baca dan ikuti terlebih dahulu petunjuk di bawah ini</h4>
                <a href="{{ route('admin.import') }}" class="btn text-white btn-sm btn-rounded btn-success sub-header"><B>Kembali</B></a>
            </div>
        </div>
	</div>

@endsection

resources/views/admin/pages/userImport.blade.php
@extends('admin.layouts.master')

@section('title', 'User Import')

@section('page-title', 'Import User')

@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card-box">
				<h4 class="header-title mb-2">Mohon baca terlebih dahulu petunjuk pengisian data user sebelum melakukan import data:</h4>
				@if (session()->has('error'))
					<div class="alert alert-danger">
						<strong>{{ session('error') }}</strong>
					</div>
				@else
					<div class="alert alert-warning">Harap cek ulang data yang anda isi. Apakah sudah benar atau belum.</div>
				@endif
                <a href="{{ route('admin.importGuide') }}" class="btn btn-sm sub-header text-white btn-rounded btn-info"><B>Kelik di sini untuk memahami lebih lanjut</B></a>
				<form action="" method="post" enctype="multipart/form-data">
					@csrf
					<div class="row">
					  	<div class="col">
							<div class="form-group">
								<label for="import">Import file:</label>
								<input id="import" type="file" name="import" class="form-control">
							</div>
					  	</div>
					</div>
					<div class="row">
						<div class="col">
							<input class="btn btn-primary" type="submit" value="Upload">
						</div>
					</div>
				</form>
            </div>
        </div>
    </div>
@endsection