routes/web.php
<?php

use UniSharp\LaravelFilemanager\Lfm;

Route::get('/', function () {
    return view('index');
});

Auth::routes(['register' => false]);
// Route::get('/home', 'HomeController@index')->name('home');

////////////
// ADMIN //
///////////
Route::name('admin.')->group(function () {
    // Auth
    Route::namespace('AdminAuth')
        ->group(function () {
            Route::get('/admin/login', 'LoginController@showLoginForm')->name('login');
            Route::post('/admin/login', 'LoginController@login')->name('login.submit');
            Route::post('/admin/logout', 'LoginController@logout')->name('logout');
    });

    // Admin
    Route::namespace('Admin')
        ->group(function () {

            // Dashboard
            Route::get('/admin', 'AdminController@index')
                ->name('home');
            
            // Topik
            Route::get('/admin/topik', 'EventController@topik')
                ->name('topik');
            Route::post('/admin/topik/add', 'EventController@topikAdd')
                ->name('topikAdd');
            Route::get('/admin/topik/edit/{id}', 'EventController@topikEdit')
                ->name('topikEdit');
            Route::post('/admin/topik/update', 'EventController@topikUpdate')
                ->name('topikUpdate');
            Route::post('/admin/topik/delete/{id}', 'EventController@topikDelete')
                ->name('topikDelete');
            Route::post('/admin/topik/aktifkan/{id}', 'EventController@aktifkan')
                ->name('topikAktifkan');
            Route::post('/admin/topik/nonaktifkan/{id}', 'EventController@nonaktifkan')
                ->name('topikNonaktifkan');
        
            // Quiz
            Route::get('/admin/quiz', 'AdminController@quiz')
                ->name('quiz');
            Route::post('/admin/quiz/add', 'AdminController@quizAdd')
                ->name('quizAdd');
            Route::get('/admin/quiz/edit/{id}', 'AdminController@quizEdit')
                ->name('quizEdit');
            Route::post('/admin/quiz/update', 'AdminController@quizUpdate')
                ->name('quizUpdate');
            Route::post('/admin/quiz/delete/{id}', 'AdminController@quizDelete')
                ->name('quizDelete');
        
            // Pertanyaan
            Route::get('/admin/pertanyaan/{id}', 'AdminController@pertanyaan')
                ->name('pertanyaan');
            Route::post('/admin/pertanyaan/image_upload', 'AdminController@pertanyaanImage')
                ->name('upload');
            Route::post('/admin/pertanyaan/add', 'AdminController@pertanyaanAdd')
                ->name('pertanyaanAdd');
            Route::get('/admin/pertanyaan/edit/{id}', 'AdminController@pertanyaanEdit')
                ->name('pertanyaanEdit');
            Route::put('/admin/pertanyaan/update', 'AdminController@pertanyaanUpdate')
                ->name('pertanyaanUpdate');
            Route::delete('/admin/pertanyaan/delete/{id}', 'AdminController@pertanyaanDelete')
                ->name('pertanyaanDelete');
        
            // Jawaban
            Route::get('/admin/jawaban/{id}', 'AdminController@jawaban')
                ->name('jawaban');
            Route::post('/admin/jawaban/add', 'AdminController@jawabanAdd')
                ->name('jawabanAdd');
            Route::get('/admin/jawaban/edit/{id}', 'AdminController@jawabanEdit')
                ->name('jawabanEdit');
            Route::put('/admin/jawaban/update', 'AdminController@jawabanUpdate')
                ->name('jawabanUpdate');
            Route::delete('/admin/jawaban/delete/{id}', 'AdminController@jawabanDelete')
                ->name('jawabanDelete');
        
            // Penilaian
            Route::get('/admin/penilaian', 'AdminController@penilaian')
                ->name('penilaian');
            Route::post('/admin/penilaian/add', 'AdminController@penilaianAdd')
                ->name('penilaianAdd');
            Route::get('/admin/penilaian/edit/{id}', 'AdminController@penilaianEdit')
                ->name('penilaianEdit');
            Route::post('/admin/penilaian/update', 'AdminController@penilaianUpdate')
                ->name('penilaianUpdate');
            Route::post('/admin/penilaian/delete/{id}', 'AdminController@penilaianDelete')
                ->name('penilaianDelete');
        
            // Bank
            Route::get('/admin/bank', 'AdminController@bank')
                ->name('bank');
            Route::post('/admin/bank/add', 'AdminController@bankAdd')
                ->name('bankAdd');
            Route::get('/admin/bank/edit/{id}', 'AdminController@bankEdit')
                ->name('bankEdit');
            Route::post('/admin/bank/update', 'AdminController@bankUpdate')
                ->name('bankUpdate');
            Route::post('/admin/bank/delete/{id}', 'AdminController@bankDelete')
                ->name('bankDelete');
            Route::post('/admin/bank/active/{id}', 'AdminController@bankActive')
                ->name('bankActive');
            Route::post('/admin/bank/inactive/{id}', 'AdminController@bankInActive')
                ->name('bankInActive');
        
            // Export/Import Excel
            Route::get('/admin/user/export/excel', 'AdminController@excel')
                ->name('excel');

            // Tambah Admin
            Route::get('/admin/tambah-admin', 'AdminController@admin')->name('tambahAdmin');
            Route::get('/admin/tambah-admin/edit/{id}', 'AdminController@editAdmin')->name('editAdmin');
            Route::post('/admin/tambah-admin/add', 'AdminController@tambahAdmin')->name('adminAdd');
            Route::post('/admin/tambah-admin/update', 'AdminController@updateAdmin')->name('adminUpdate');
            Route::post('/admin/tambah-admin/delete/{id}', 'AdminController@deleteAdmin')->name('adminDelete');
        
            // User
            Route::get('/admin/user', 'UserController@user')
                ->name('user');
            Route::get('/admin/user/add', 'UserController@userAdd')
                ->name('userAdd');
            Route::post('/admin/user/kota', 'UserController@kota')
                ->name('kota');
            Route::post('/admin/user/insert', 'UserController@userInsert')
                ->name('userInsert');
            Route::post('/admin/user/active/{id}', 'UserController@userActive')
                ->name('userActive');
            Route::post('/admin/user/inactive/{id}', 'UserController@userInactive')
                ->name('userInactive');
            Route::post('/admin/user/delete/{id}', 'UserController@userDelete')
                ->name('userDelete');
            Route::get('/admin/user/detail/{id}', 'UserController@userDetail')
                ->name('userDetail');
        
            // Pembayaran
            Route::get('/admin/pembayaran', 'AdminController@pembayaran')
                ->name('pembayaran');
            Route::get('/admin/pembayaran/bukti/{id}', 'AdminController@pembayaranBukti')
                ->name('pembayaranBukti');
            Route::post('/admin/pembayaran/confirm/{id}', 'AdminController@pembayaranConfirm')
                ->name('pembayaranConfirm');
            Route::post('/admin/pembayaran/batal/{id}', 'AdminController@pembayaranBatal')
                ->name('pembayaranBatal');

            // Sertifikat
            Route::get('/admin/sertifikat', 'AdminController@sertifikat')
            ->name('sertifikat');    
        
            // Leaderboard
            Route::get('/admin/leaderboard', 'LeaderboardController@leaderboard')
                ->name('leaderboard');
            Route::get('/admin/leaderboard/result', 'LeaderboardController@leaderboardResult')
                ->name('leaderboardResult');
        });

    // Import Controller
    Route::get('/admin/user/import/excel', 'ImportController@userImport')
        ->name('import');
    Route::post('/admin/user/import/excel', 'ImportController@importStore')
        ->name('import.submit');
    Route::get('/admin/user/import/panduan', 'ImportController@importGuide')
        ->name('importGuide');
});

Route::group(['prefix' => 'filemanager'], function() {
    Lfm::routes();
});

//////////
// USER //
//////////
Route::name('user.')
    ->group(function () {
        // Auth
        Route::namespace('Auth')
            ->group(function () {
                Route::post('/user/logout', 'LoginController@logoutUser')
                    ->name('logout');
            });
        
        // User
        Route::namespace('User')
            ->group(function () {
                Route::get('/dashboard', 'UserController@index')
                    ->name('dashboard');
                Route::get('/pembayaran', 'UserController@pembayaran')
                    ->name('pembayaran');
                Route::get('/konfirmasi', 'UserController@konfirmasi')
                    ->name('konfirmasi');
                Route::post('/konfirmasi/add', 'UserController@konfirmasiAdd')
                    ->name('konfirmasiAdd');
                Route::get('/status', 'UserController@status')
                    ->name('status');
                Route::get('/exampaper', 'ExampaperController@exampaper')
                    ->name('exampaper');
                Route::get('/exampaper/notfound', 'ExampaperController@notfound')
                    ->name('notfound');
                Route::get('/exampaper/berakhir', 'ExampaperController@berakhir')
                    ->name('berakhir');
                Route::get('/exampaper/kosong', 'ExampaperController@kosong')
                    ->name('kosong');
                Route::get('/lembarsoal/{kode_soal}', 'ExampaperController@lembarsoal')
                    ->name('lembarsoal');
                Route::post('/lembarsoal/submit', 'ExampaperController@storeTest')
                    ->name('storeTest');
            });
});

resources/views/admin/partials/_footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                2020 InSightMarComm. &copy;{{-- Adminox theme by <a href="#">Coderthemes</a> --}}
            </div>
        </div>
    </div>
</footer>

resources/views/admin/partials/_head.blade.php
<meta name="csrf-token" content="{{ csrf_token() }}"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- App favicon -->
<link rel="shortcut icon" href="{{ asset('assets/images/favicon.ico') }}">

<!-- C3 Chart css -->
<link href="{{ asset('assets/libs/c3/c3.min.css') }}" rel="stylesheet" type="text/css" />
<!-- third party css -->
<link href="{{ asset('assets/libs/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/libs/datatables/buttons.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/libs/datatables/responsive.bootstrap4.css') }}" rel="stylesheet" type="text/css" />
<!-- App css -->
<link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" id="bootstrap-stylesheet" />
<link href="{{ asset('assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/css/app.min.css') }}" rel="stylesheet" type="text/css"  id="app-stylesheet" />
<link href="{{ asset('css/sweetalert2.min.css') }}" rel="stylesheet" type="text/css"  id="app-stylesheet" />
<link href="{{asset('css/select2.min.css')}}" rel="stylesheet" type="text/css" id="app-stylesheet" />
<link href="{{asset('css/gijgo.min.css')}}" rel="stylesheet" type="text/css" id="app-stylesheet" />
<link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepickers.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/parsley.css') }}">

resources/views/admin/partials/_navbar.blade.php
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">

        {{-- <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle  waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <i class="dripicons-bell noti-icon"></i>
                <span class="badge badge-pink rounded-circle noti-icon-badge">4</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-lg">
                <div class="dropdown-header noti-title">
                    <h5 class="text-overflow m-0">
                        <span class="float-right">
                            <span class="badge badge-danger float-right">5</span>
                        </span>Notification
                    </h5>
                </div>
                <div class="slimscroll noti-scroll">
                    <!-- <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-success"><i class="mdi mdi-comment-account-outline"></i></div>
                        <p class="notify-details">Robert S. Taylor commented on Admin<small class="text-muted">1 min ago</small></p>
                    </a> -->

                    <!-- item-->
                    <!-- <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-primary">
                            <i class="mdi mdi-settings-outline"></i>
                        </div>
                        <p class="notify-details">New settings
                            <small class="text-muted">There are new settings available</small>
                        </p>
                    </a> -->
                </div>

                <!-- All-->
                <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                    View all
                    <i class="fi-arrow-right"></i>
                </a>

            </div>
        </li> --}}

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <img src="{{ asset('img/male.png') }}" alt="user-image" class="rounded-circle">
                <span class="pro-user-name ml-1">
                    {{ Auth::user()->name }}  <i class="mdi mdi-chevron-down"></i> 
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>
                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="fe-settings"></i>
                    <span>Settings</span>
                </a>
                <div class="dropdown-divider"></div>
                <!-- item-->
                <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="dropdown-item notify-item">
                    <i class="fe-log-out"></i>
                    <span>{{ __('Logout') }}</span>
                </a>
                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>

            </div>
        </li>
    </ul>

    <!-- LOGO -->
    <div class="logo-box">
        <a href="#" class="logo text-center">
            <span class="logo-lg">
                <img src="{{ asset('img/posi.png') }}" alt="" height="50">
                <!-- <span class="logo-lg-text-light">UBold</span> -->
            </span>
            <span class="logo-sm">
                <!-- <span class="logo-sm-text-dark">U</span> -->
                <img src="{{ asset('img/posi.png') }}" alt="" height="15">
            </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <li>
            <button class="button-menu-mobile waves-effect waves-light">
                <i class="fe-menu"></i>
            </button>
        </li>
    </ul>
</div>

resources/views/admin/partials/_scripts.blade.php
        <script src="{{ asset('assets/js/vendor.min.js') }}"></script>
        <!--C3 Chart-->
        <script src="{{ asset('assets/libs/d3/d3.min.js') }}"></script>
        <script src="{{ asset('assets/libs/c3/c3.min.js') }}"></script>
        <script src="{{ asset('assets/js/pages/c3.init.js') }}"></script>
        <script src="{{ asset('assets/libs/echarts/echarts.min.js') }}"></script>
        <script src="{{ asset('assets/js/pages/dashboard.init.js') }}"></script>
        <!-- Required datatable js -->
        <script src="{{ asset('assets/libs/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('assets/libs/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <!-- Responsive examples -->
        <script src="{{ asset('assets/libs/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ asset('assets/libs/datatables/responsive.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('js/gijgo.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap-datetimepickers.min.js') }}"></script>
        {{-- <script src="{{ asset('js/bootstrap-datepicker.id.min.js') }}"></script> --}}
        <script src="{{ asset('js/sweetalert2.all.min.js') }}"></script>
        <script src="{{ asset('js/parsley.js') }}"></script>
        <script src="{{ asset('js/jquery.validate.min.js') }}"></script>
        <!-- App js -->
        <script src="{{ asset('assets/js/app.min.js') }}"></script>

resources/views/admin/partials/_sidebar.blade.php
<div class="left-side-menu">
    <div class="slimscroll-menu">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <ul class="metismenu" id="side-menu">
                <li class="menu-title">Navigasi Menu</li>
                
                <li>
                    <a href="{{ route('admin.home') }}">
                        <i class="fe-airplay"></i>
                        <span> Dashboard </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.leaderboard') }}">
                        <i class="mdi mdi-sword-cross"></i>
                        <span> Leaderboard </span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);">
                        <i class="fe-sidebar"></i>
                        <span>  Modul </span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li><a href="{{ route('admin.topik') }}"><i class="mdi mdi-content-paste "></i> Event-Bidang</a></li>
                        <li><a href="{{ route('admin.quiz') }}"><i class="mdi mdi-file-document-box-outline"></i> Quiz</a></li>
                        <li><a href="#"><i class="mdi mdi-check-underline"></i> Result</a></li>
                    </ul>
                </li>

                <li>
                    <a href="{{ route('admin.penilaian') }}">
                        <i class="mdi mdi-chart-timeline"></i>
                        <span> Penilaian </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.user') }}">
                        <i class="icon-people"></i>
                        <span> User </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.pembayaran') }}">
                        <i class="mdi mdi-cash-multiple"></i>
                        <span> Pembayaran </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.bank') }}">
                        <i class="mdi mdi-bank"></i>
                        <span> Rekening </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.sertifikat') }}">
                        <i class="mdi mdi-file-document"></i>
                        <span> Sertifikat </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admin.tambahAdmin') }}">
                        <i class="mdi mdi-account"></i>
                        <span> Admin </span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- End Sidebar -->
        <div class="clearfix"></div>
    </div>
    <!-- Sidebar -left -->
</div>